FROM python:3.7-slim-stretch

# timezone handler 
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Paris 

# initial system requirements 
RUN apt-get update --fix-missing && \
    apt-get install --yes --no-install-recommends \
        tzdata apt-utils dialog gcc git curl pkg-config build-essential ffmpeg 

# user creation 
RUN useradd --gid root --create-home solver 
WORKDIR /home/solver 

# virtualenv 
ENV VIRTUAL_ENV=/opt/venv 
RUN chmod -R g+rwx /home/solver && python -m venv $VIRTUAL_ENV --system-site-packages 
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

COPY requirements-cpu.txt ./ 

# python requirements 
RUN pip install --upgrade pip && pip install -r requirements-cpu.txt 
RUN pip install pydub && nltk 
# pull source code 
COPY . ./ 

# environment variables 
ENV MODELS="models"
ENV TRANSFORMERS_CACHE="models/cache"

# entrypoint 
ENTRYPOINT ["python", "main.py"]
CMD ["--debug"]
